spring.application.name=order-service

spring.config.import=optional:configserver:http://localhost:8888

# ==============================
# Eureka
# ==============================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

# ==============================
# PostgreSQL
# ==============================

spring.datasource.url=jdbc:postgresql://localhost:5432/armalora_order_db
spring.datasource.username=postgres
spring.datasource.password=postgre

# ==============================
# JPA / Hibernate
# ==============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# ==============================
# Actuator
# ==============================

management.endpoints.web.exposure.include=health